trigger:
  - master
pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DownloadGitHubRelease@0
    inputs:
      gitHubConnection: 'thedevyashsaini' 
      repositoryName: 'thedevyashsaini/rusticle'
      releaseId: 'latest'
      assets: 'rusticle' 
      downloadPath: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Download release from GitHub'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'rust-build'
    displayName: 'Publish build artifacts'