name: Build and Test Rust Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build the Project
      run: cargo build --release

    - name: Run Tests
      run: cargo test --verbose

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-binaries
        path: target/release/

    - name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.sha }}
        release_name: Build-${{ github.sha }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: target/release/rusticle
        asset_name: rusticle
        asset_content_type: application/octet-stream